"""Tests for NCData base class timestamp behavior."""

import time

from neuracore_types.nc_data.nc_data import NCData


class TestNCDataTimestamps:
    """Tests for NCData timestamp and published_time behavior."""

    def test_no_timestamp_provided_matches_published_time(self):
        """When no timestamp is provided, it should equal published_time."""
        data = NCData()
        assert data.timestamp == data.published_time

    def test_manual_timestamp_preserved(self):
        """When timestamp is manually set, it should be preserved."""
        manual_ts = 1000.0
        data = NCData(timestamp=manual_ts)
        assert data.timestamp == manual_ts
        assert data.published_time != manual_ts

    def test_published_time_always_autogenerated(self):
        """published_time should always be auto-generated close to now."""
        now = time.time()
        data = NCData(timestamp=1000.0)
        assert abs(data.published_time - now) < 1.0
