// source: neuracore_types.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

goog.exportSymbol('proto.neuracore_types.CameraData', null, global);
goog.exportSymbol('proto.neuracore_types.CustomData', null, global);
goog.exportSymbol('proto.neuracore_types.EndEffectorData', null, global);
goog.exportSymbol('proto.neuracore_types.EndEffectorPoseData', null, global);
goog.exportSymbol('proto.neuracore_types.FloatRow', null, global);
goog.exportSymbol('proto.neuracore_types.JointData', null, global);
goog.exportSymbol('proto.neuracore_types.LanguageData', null, global);
goog.exportSymbol('proto.neuracore_types.ParallelGripperOpenAmountData', null, global);
goog.exportSymbol('proto.neuracore_types.PointCloudData', null, global);
goog.exportSymbol('proto.neuracore_types.PoseData', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.neuracore_types.FloatRow = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.neuracore_types.FloatRow.repeatedFields_, null);
};
goog.inherits(proto.neuracore_types.FloatRow, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.neuracore_types.FloatRow.displayName = 'proto.neuracore_types.FloatRow';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.neuracore_types.JointData = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.neuracore_types.JointData, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.neuracore_types.JointData.displayName = 'proto.neuracore_types.JointData';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.neuracore_types.CameraData = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.neuracore_types.CameraData.repeatedFields_, null);
};
goog.inherits(proto.neuracore_types.CameraData, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.neuracore_types.CameraData.displayName = 'proto.neuracore_types.CameraData';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.neuracore_types.PoseData = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.neuracore_types.PoseData, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.neuracore_types.PoseData.displayName = 'proto.neuracore_types.PoseData';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.neuracore_types.EndEffectorData = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.neuracore_types.EndEffectorData, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.neuracore_types.EndEffectorData.displayName = 'proto.neuracore_types.EndEffectorData';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.neuracore_types.EndEffectorPoseData = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.neuracore_types.EndEffectorPoseData, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.neuracore_types.EndEffectorPoseData.displayName = 'proto.neuracore_types.EndEffectorPoseData';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.neuracore_types.ParallelGripperOpenAmountData = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.neuracore_types.ParallelGripperOpenAmountData, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.neuracore_types.ParallelGripperOpenAmountData.displayName = 'proto.neuracore_types.ParallelGripperOpenAmountData';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.neuracore_types.PointCloudData = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.neuracore_types.PointCloudData, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.neuracore_types.PointCloudData.displayName = 'proto.neuracore_types.PointCloudData';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.neuracore_types.LanguageData = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.neuracore_types.LanguageData, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.neuracore_types.LanguageData.displayName = 'proto.neuracore_types.LanguageData';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.neuracore_types.CustomData = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.neuracore_types.CustomData, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.neuracore_types.CustomData.displayName = 'proto.neuracore_types.CustomData';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.neuracore_types.FloatRow.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.neuracore_types.FloatRow.prototype.toObject = function(opt_includeInstance) {
  return proto.neuracore_types.FloatRow.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.neuracore_types.FloatRow} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.neuracore_types.FloatRow.toObject = function(includeInstance, msg) {
  var f, obj = {
valuesList: (f = jspb.Message.getRepeatedFloatingPointField(msg, 1)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.neuracore_types.FloatRow}
 */
proto.neuracore_types.FloatRow.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.neuracore_types.FloatRow;
  return proto.neuracore_types.FloatRow.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.neuracore_types.FloatRow} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.neuracore_types.FloatRow}
 */
proto.neuracore_types.FloatRow.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedFloat() : [reader.readFloat()]);
      for (var i = 0; i < values.length; i++) {
        msg.addValues(values[i]);
      }
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.neuracore_types.FloatRow.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.neuracore_types.FloatRow.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.neuracore_types.FloatRow} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.neuracore_types.FloatRow.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getValuesList();
  if (f.length > 0) {
    writer.writePackedFloat(
      1,
      f
    );
  }
};


/**
 * repeated float values = 1;
 * @return {!Array<number>}
 */
proto.neuracore_types.FloatRow.prototype.getValuesList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 1));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.neuracore_types.FloatRow} returns this
 */
proto.neuracore_types.FloatRow.prototype.setValuesList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.neuracore_types.FloatRow} returns this
 */
proto.neuracore_types.FloatRow.prototype.addValues = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.neuracore_types.FloatRow} returns this
 */
proto.neuracore_types.FloatRow.prototype.clearValuesList = function() {
  return this.setValuesList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.neuracore_types.JointData.prototype.toObject = function(opt_includeInstance) {
  return proto.neuracore_types.JointData.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.neuracore_types.JointData} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.neuracore_types.JointData.toObject = function(includeInstance, msg) {
  var f, obj = {
timestamp: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0),
valuesMap: (f = msg.getValuesMap()) ? f.toObject(includeInstance, undefined) : [],
additionalValuesMap: (f = msg.getAdditionalValuesMap()) ? f.toObject(includeInstance, undefined) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.neuracore_types.JointData}
 */
proto.neuracore_types.JointData.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.neuracore_types.JointData;
  return proto.neuracore_types.JointData.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.neuracore_types.JointData} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.neuracore_types.JointData}
 */
proto.neuracore_types.JointData.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setTimestamp(value);
      break;
    case 2:
      var value = msg.getValuesMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readDouble, null, "", 0.0);
         });
      break;
    case 3:
      var value = msg.getAdditionalValuesMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readDouble, null, "", 0.0);
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.neuracore_types.JointData.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.neuracore_types.JointData.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.neuracore_types.JointData} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.neuracore_types.JointData.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTimestamp();
  if (f !== 0.0) {
    writer.writeDouble(
      1,
      f
    );
  }
  f = message.getValuesMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(2, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeDouble);
  }
  f = message.getAdditionalValuesMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(3, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeDouble);
  }
};


/**
 * optional double timestamp = 1;
 * @return {number}
 */
proto.neuracore_types.JointData.prototype.getTimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.neuracore_types.JointData} returns this
 */
proto.neuracore_types.JointData.prototype.setTimestamp = function(value) {
  return jspb.Message.setProto3FloatField(this, 1, value);
};


/**
 * map<string, double> values = 2;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,number>}
 */
proto.neuracore_types.JointData.prototype.getValuesMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,number>} */ (
      jspb.Message.getMapField(this, 2, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.neuracore_types.JointData} returns this
 */
proto.neuracore_types.JointData.prototype.clearValuesMap = function() {
  this.getValuesMap().clear();
  return this;
};


/**
 * map<string, double> additional_values = 3;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,number>}
 */
proto.neuracore_types.JointData.prototype.getAdditionalValuesMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,number>} */ (
      jspb.Message.getMapField(this, 3, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.neuracore_types.JointData} returns this
 */
proto.neuracore_types.JointData.prototype.clearAdditionalValuesMap = function() {
  this.getAdditionalValuesMap().clear();
  return this;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.neuracore_types.CameraData.repeatedFields_ = [3,4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.neuracore_types.CameraData.prototype.toObject = function(opt_includeInstance) {
  return proto.neuracore_types.CameraData.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.neuracore_types.CameraData} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.neuracore_types.CameraData.toObject = function(includeInstance, msg) {
  var f, obj = {
timestamp: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0),
frameIdx: jspb.Message.getFieldWithDefault(msg, 2, 0),
extrinsicsList: jspb.Message.toObjectList(msg.getExtrinsicsList(),
    proto.neuracore_types.FloatRow.toObject, includeInstance),
intrinsicsList: jspb.Message.toObjectList(msg.getIntrinsicsList(),
    proto.neuracore_types.FloatRow.toObject, includeInstance),
frame: msg.getFrame_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.neuracore_types.CameraData}
 */
proto.neuracore_types.CameraData.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.neuracore_types.CameraData;
  return proto.neuracore_types.CameraData.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.neuracore_types.CameraData} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.neuracore_types.CameraData}
 */
proto.neuracore_types.CameraData.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setTimestamp(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setFrameIdx(value);
      break;
    case 3:
      var value = new proto.neuracore_types.FloatRow;
      reader.readMessage(value,proto.neuracore_types.FloatRow.deserializeBinaryFromReader);
      msg.addExtrinsics(value);
      break;
    case 4:
      var value = new proto.neuracore_types.FloatRow;
      reader.readMessage(value,proto.neuracore_types.FloatRow.deserializeBinaryFromReader);
      msg.addIntrinsics(value);
      break;
    case 5:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setFrame(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.neuracore_types.CameraData.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.neuracore_types.CameraData.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.neuracore_types.CameraData} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.neuracore_types.CameraData.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTimestamp();
  if (f !== 0.0) {
    writer.writeDouble(
      1,
      f
    );
  }
  f = message.getFrameIdx();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getExtrinsicsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.neuracore_types.FloatRow.serializeBinaryToWriter
    );
  }
  f = message.getIntrinsicsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.neuracore_types.FloatRow.serializeBinaryToWriter
    );
  }
  f = message.getFrame_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      5,
      f
    );
  }
};


/**
 * optional double timestamp = 1;
 * @return {number}
 */
proto.neuracore_types.CameraData.prototype.getTimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.neuracore_types.CameraData} returns this
 */
proto.neuracore_types.CameraData.prototype.setTimestamp = function(value) {
  return jspb.Message.setProto3FloatField(this, 1, value);
};


/**
 * optional int32 frame_idx = 2;
 * @return {number}
 */
proto.neuracore_types.CameraData.prototype.getFrameIdx = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.neuracore_types.CameraData} returns this
 */
proto.neuracore_types.CameraData.prototype.setFrameIdx = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * repeated FloatRow extrinsics = 3;
 * @return {!Array<!proto.neuracore_types.FloatRow>}
 */
proto.neuracore_types.CameraData.prototype.getExtrinsicsList = function() {
  return /** @type{!Array<!proto.neuracore_types.FloatRow>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.neuracore_types.FloatRow, 3));
};


/**
 * @param {!Array<!proto.neuracore_types.FloatRow>} value
 * @return {!proto.neuracore_types.CameraData} returns this
*/
proto.neuracore_types.CameraData.prototype.setExtrinsicsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.neuracore_types.FloatRow=} opt_value
 * @param {number=} opt_index
 * @return {!proto.neuracore_types.FloatRow}
 */
proto.neuracore_types.CameraData.prototype.addExtrinsics = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.neuracore_types.FloatRow, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.neuracore_types.CameraData} returns this
 */
proto.neuracore_types.CameraData.prototype.clearExtrinsicsList = function() {
  return this.setExtrinsicsList([]);
};


/**
 * repeated FloatRow intrinsics = 4;
 * @return {!Array<!proto.neuracore_types.FloatRow>}
 */
proto.neuracore_types.CameraData.prototype.getIntrinsicsList = function() {
  return /** @type{!Array<!proto.neuracore_types.FloatRow>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.neuracore_types.FloatRow, 4));
};


/**
 * @param {!Array<!proto.neuracore_types.FloatRow>} value
 * @return {!proto.neuracore_types.CameraData} returns this
*/
proto.neuracore_types.CameraData.prototype.setIntrinsicsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.neuracore_types.FloatRow=} opt_value
 * @param {number=} opt_index
 * @return {!proto.neuracore_types.FloatRow}
 */
proto.neuracore_types.CameraData.prototype.addIntrinsics = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.neuracore_types.FloatRow, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.neuracore_types.CameraData} returns this
 */
proto.neuracore_types.CameraData.prototype.clearIntrinsicsList = function() {
  return this.setIntrinsicsList([]);
};


/**
 * optional bytes frame = 5;
 * @return {!(string|Uint8Array)}
 */
proto.neuracore_types.CameraData.prototype.getFrame = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * optional bytes frame = 5;
 * This is a type-conversion wrapper around `getFrame()`
 * @return {string}
 */
proto.neuracore_types.CameraData.prototype.getFrame_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getFrame()));
};


/**
 * optional bytes frame = 5;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getFrame()`
 * @return {!Uint8Array}
 */
proto.neuracore_types.CameraData.prototype.getFrame_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getFrame()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.neuracore_types.CameraData} returns this
 */
proto.neuracore_types.CameraData.prototype.setFrame = function(value) {
  return jspb.Message.setProto3BytesField(this, 5, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.neuracore_types.PoseData.prototype.toObject = function(opt_includeInstance) {
  return proto.neuracore_types.PoseData.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.neuracore_types.PoseData} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.neuracore_types.PoseData.toObject = function(includeInstance, msg) {
  var f, obj = {
timestamp: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0),
poseMap: (f = msg.getPoseMap()) ? f.toObject(includeInstance, proto.neuracore_types.FloatRow.toObject) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.neuracore_types.PoseData}
 */
proto.neuracore_types.PoseData.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.neuracore_types.PoseData;
  return proto.neuracore_types.PoseData.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.neuracore_types.PoseData} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.neuracore_types.PoseData}
 */
proto.neuracore_types.PoseData.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setTimestamp(value);
      break;
    case 2:
      var value = msg.getPoseMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.neuracore_types.FloatRow.deserializeBinaryFromReader, "", new proto.neuracore_types.FloatRow());
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.neuracore_types.PoseData.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.neuracore_types.PoseData.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.neuracore_types.PoseData} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.neuracore_types.PoseData.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTimestamp();
  if (f !== 0.0) {
    writer.writeDouble(
      1,
      f
    );
  }
  f = message.getPoseMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(2, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.neuracore_types.FloatRow.serializeBinaryToWriter);
  }
};


/**
 * optional double timestamp = 1;
 * @return {number}
 */
proto.neuracore_types.PoseData.prototype.getTimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.neuracore_types.PoseData} returns this
 */
proto.neuracore_types.PoseData.prototype.setTimestamp = function(value) {
  return jspb.Message.setProto3FloatField(this, 1, value);
};


/**
 * map<string, FloatRow> pose = 2;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.neuracore_types.FloatRow>}
 */
proto.neuracore_types.PoseData.prototype.getPoseMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.neuracore_types.FloatRow>} */ (
      jspb.Message.getMapField(this, 2, opt_noLazyCreate,
      proto.neuracore_types.FloatRow));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.neuracore_types.PoseData} returns this
 */
proto.neuracore_types.PoseData.prototype.clearPoseMap = function() {
  this.getPoseMap().clear();
  return this;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.neuracore_types.EndEffectorData.prototype.toObject = function(opt_includeInstance) {
  return proto.neuracore_types.EndEffectorData.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.neuracore_types.EndEffectorData} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.neuracore_types.EndEffectorData.toObject = function(includeInstance, msg) {
  var f, obj = {
timestamp: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0),
openAmountsMap: (f = msg.getOpenAmountsMap()) ? f.toObject(includeInstance, undefined) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.neuracore_types.EndEffectorData}
 */
proto.neuracore_types.EndEffectorData.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.neuracore_types.EndEffectorData;
  return proto.neuracore_types.EndEffectorData.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.neuracore_types.EndEffectorData} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.neuracore_types.EndEffectorData}
 */
proto.neuracore_types.EndEffectorData.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setTimestamp(value);
      break;
    case 2:
      var value = msg.getOpenAmountsMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readDouble, null, "", 0.0);
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.neuracore_types.EndEffectorData.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.neuracore_types.EndEffectorData.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.neuracore_types.EndEffectorData} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.neuracore_types.EndEffectorData.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTimestamp();
  if (f !== 0.0) {
    writer.writeDouble(
      1,
      f
    );
  }
  f = message.getOpenAmountsMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(2, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeDouble);
  }
};


/**
 * optional double timestamp = 1;
 * @return {number}
 */
proto.neuracore_types.EndEffectorData.prototype.getTimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.neuracore_types.EndEffectorData} returns this
 */
proto.neuracore_types.EndEffectorData.prototype.setTimestamp = function(value) {
  return jspb.Message.setProto3FloatField(this, 1, value);
};


/**
 * map<string, double> open_amounts = 2;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,number>}
 */
proto.neuracore_types.EndEffectorData.prototype.getOpenAmountsMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,number>} */ (
      jspb.Message.getMapField(this, 2, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.neuracore_types.EndEffectorData} returns this
 */
proto.neuracore_types.EndEffectorData.prototype.clearOpenAmountsMap = function() {
  this.getOpenAmountsMap().clear();
  return this;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.neuracore_types.EndEffectorPoseData.prototype.toObject = function(opt_includeInstance) {
  return proto.neuracore_types.EndEffectorPoseData.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.neuracore_types.EndEffectorPoseData} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.neuracore_types.EndEffectorPoseData.toObject = function(includeInstance, msg) {
  var f, obj = {
timestamp: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0),
posesMap: (f = msg.getPosesMap()) ? f.toObject(includeInstance, proto.neuracore_types.FloatRow.toObject) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.neuracore_types.EndEffectorPoseData}
 */
proto.neuracore_types.EndEffectorPoseData.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.neuracore_types.EndEffectorPoseData;
  return proto.neuracore_types.EndEffectorPoseData.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.neuracore_types.EndEffectorPoseData} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.neuracore_types.EndEffectorPoseData}
 */
proto.neuracore_types.EndEffectorPoseData.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setTimestamp(value);
      break;
    case 2:
      var value = msg.getPosesMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.neuracore_types.FloatRow.deserializeBinaryFromReader, "", new proto.neuracore_types.FloatRow());
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.neuracore_types.EndEffectorPoseData.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.neuracore_types.EndEffectorPoseData.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.neuracore_types.EndEffectorPoseData} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.neuracore_types.EndEffectorPoseData.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTimestamp();
  if (f !== 0.0) {
    writer.writeDouble(
      1,
      f
    );
  }
  f = message.getPosesMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(2, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.neuracore_types.FloatRow.serializeBinaryToWriter);
  }
};


/**
 * optional double timestamp = 1;
 * @return {number}
 */
proto.neuracore_types.EndEffectorPoseData.prototype.getTimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.neuracore_types.EndEffectorPoseData} returns this
 */
proto.neuracore_types.EndEffectorPoseData.prototype.setTimestamp = function(value) {
  return jspb.Message.setProto3FloatField(this, 1, value);
};


/**
 * map<string, FloatRow> poses = 2;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.neuracore_types.FloatRow>}
 */
proto.neuracore_types.EndEffectorPoseData.prototype.getPosesMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.neuracore_types.FloatRow>} */ (
      jspb.Message.getMapField(this, 2, opt_noLazyCreate,
      proto.neuracore_types.FloatRow));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.neuracore_types.EndEffectorPoseData} returns this
 */
proto.neuracore_types.EndEffectorPoseData.prototype.clearPosesMap = function() {
  this.getPosesMap().clear();
  return this;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.neuracore_types.ParallelGripperOpenAmountData.prototype.toObject = function(opt_includeInstance) {
  return proto.neuracore_types.ParallelGripperOpenAmountData.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.neuracore_types.ParallelGripperOpenAmountData} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.neuracore_types.ParallelGripperOpenAmountData.toObject = function(includeInstance, msg) {
  var f, obj = {
timestamp: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0),
openAmountsMap: (f = msg.getOpenAmountsMap()) ? f.toObject(includeInstance, undefined) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.neuracore_types.ParallelGripperOpenAmountData}
 */
proto.neuracore_types.ParallelGripperOpenAmountData.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.neuracore_types.ParallelGripperOpenAmountData;
  return proto.neuracore_types.ParallelGripperOpenAmountData.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.neuracore_types.ParallelGripperOpenAmountData} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.neuracore_types.ParallelGripperOpenAmountData}
 */
proto.neuracore_types.ParallelGripperOpenAmountData.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setTimestamp(value);
      break;
    case 2:
      var value = msg.getOpenAmountsMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readDouble, null, "", 0.0);
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.neuracore_types.ParallelGripperOpenAmountData.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.neuracore_types.ParallelGripperOpenAmountData.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.neuracore_types.ParallelGripperOpenAmountData} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.neuracore_types.ParallelGripperOpenAmountData.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTimestamp();
  if (f !== 0.0) {
    writer.writeDouble(
      1,
      f
    );
  }
  f = message.getOpenAmountsMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(2, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeDouble);
  }
};


/**
 * optional double timestamp = 1;
 * @return {number}
 */
proto.neuracore_types.ParallelGripperOpenAmountData.prototype.getTimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.neuracore_types.ParallelGripperOpenAmountData} returns this
 */
proto.neuracore_types.ParallelGripperOpenAmountData.prototype.setTimestamp = function(value) {
  return jspb.Message.setProto3FloatField(this, 1, value);
};


/**
 * map<string, double> open_amounts = 2;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,number>}
 */
proto.neuracore_types.ParallelGripperOpenAmountData.prototype.getOpenAmountsMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,number>} */ (
      jspb.Message.getMapField(this, 2, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.neuracore_types.ParallelGripperOpenAmountData} returns this
 */
proto.neuracore_types.ParallelGripperOpenAmountData.prototype.clearOpenAmountsMap = function() {
  this.getOpenAmountsMap().clear();
  return this;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.neuracore_types.PointCloudData.prototype.toObject = function(opt_includeInstance) {
  return proto.neuracore_types.PointCloudData.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.neuracore_types.PointCloudData} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.neuracore_types.PointCloudData.toObject = function(includeInstance, msg) {
  var f, obj = {
timestamp: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0),
points: msg.getPoints_asB64(),
rgbPoints: msg.getRgbPoints_asB64(),
extrinsics: msg.getExtrinsics_asB64(),
intrinsics: msg.getIntrinsics_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.neuracore_types.PointCloudData}
 */
proto.neuracore_types.PointCloudData.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.neuracore_types.PointCloudData;
  return proto.neuracore_types.PointCloudData.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.neuracore_types.PointCloudData} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.neuracore_types.PointCloudData}
 */
proto.neuracore_types.PointCloudData.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setTimestamp(value);
      break;
    case 2:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setPoints(value);
      break;
    case 3:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setRgbPoints(value);
      break;
    case 4:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setExtrinsics(value);
      break;
    case 5:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setIntrinsics(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.neuracore_types.PointCloudData.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.neuracore_types.PointCloudData.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.neuracore_types.PointCloudData} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.neuracore_types.PointCloudData.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTimestamp();
  if (f !== 0.0) {
    writer.writeDouble(
      1,
      f
    );
  }
  f = message.getPoints_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      2,
      f
    );
  }
  f = message.getRgbPoints_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      3,
      f
    );
  }
  f = message.getExtrinsics_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      4,
      f
    );
  }
  f = message.getIntrinsics_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      5,
      f
    );
  }
};


/**
 * optional double timestamp = 1;
 * @return {number}
 */
proto.neuracore_types.PointCloudData.prototype.getTimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.neuracore_types.PointCloudData} returns this
 */
proto.neuracore_types.PointCloudData.prototype.setTimestamp = function(value) {
  return jspb.Message.setProto3FloatField(this, 1, value);
};


/**
 * optional bytes points = 2;
 * @return {!(string|Uint8Array)}
 */
proto.neuracore_types.PointCloudData.prototype.getPoints = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * optional bytes points = 2;
 * This is a type-conversion wrapper around `getPoints()`
 * @return {string}
 */
proto.neuracore_types.PointCloudData.prototype.getPoints_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getPoints()));
};


/**
 * optional bytes points = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getPoints()`
 * @return {!Uint8Array}
 */
proto.neuracore_types.PointCloudData.prototype.getPoints_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getPoints()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.neuracore_types.PointCloudData} returns this
 */
proto.neuracore_types.PointCloudData.prototype.setPoints = function(value) {
  return jspb.Message.setProto3BytesField(this, 2, value);
};


/**
 * optional bytes rgb_points = 3;
 * @return {!(string|Uint8Array)}
 */
proto.neuracore_types.PointCloudData.prototype.getRgbPoints = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * optional bytes rgb_points = 3;
 * This is a type-conversion wrapper around `getRgbPoints()`
 * @return {string}
 */
proto.neuracore_types.PointCloudData.prototype.getRgbPoints_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getRgbPoints()));
};


/**
 * optional bytes rgb_points = 3;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getRgbPoints()`
 * @return {!Uint8Array}
 */
proto.neuracore_types.PointCloudData.prototype.getRgbPoints_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getRgbPoints()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.neuracore_types.PointCloudData} returns this
 */
proto.neuracore_types.PointCloudData.prototype.setRgbPoints = function(value) {
  return jspb.Message.setProto3BytesField(this, 3, value);
};


/**
 * optional bytes extrinsics = 4;
 * @return {!(string|Uint8Array)}
 */
proto.neuracore_types.PointCloudData.prototype.getExtrinsics = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * optional bytes extrinsics = 4;
 * This is a type-conversion wrapper around `getExtrinsics()`
 * @return {string}
 */
proto.neuracore_types.PointCloudData.prototype.getExtrinsics_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getExtrinsics()));
};


/**
 * optional bytes extrinsics = 4;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getExtrinsics()`
 * @return {!Uint8Array}
 */
proto.neuracore_types.PointCloudData.prototype.getExtrinsics_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getExtrinsics()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.neuracore_types.PointCloudData} returns this
 */
proto.neuracore_types.PointCloudData.prototype.setExtrinsics = function(value) {
  return jspb.Message.setProto3BytesField(this, 4, value);
};


/**
 * optional bytes intrinsics = 5;
 * @return {!(string|Uint8Array)}
 */
proto.neuracore_types.PointCloudData.prototype.getIntrinsics = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * optional bytes intrinsics = 5;
 * This is a type-conversion wrapper around `getIntrinsics()`
 * @return {string}
 */
proto.neuracore_types.PointCloudData.prototype.getIntrinsics_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getIntrinsics()));
};


/**
 * optional bytes intrinsics = 5;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getIntrinsics()`
 * @return {!Uint8Array}
 */
proto.neuracore_types.PointCloudData.prototype.getIntrinsics_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getIntrinsics()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.neuracore_types.PointCloudData} returns this
 */
proto.neuracore_types.PointCloudData.prototype.setIntrinsics = function(value) {
  return jspb.Message.setProto3BytesField(this, 5, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.neuracore_types.LanguageData.prototype.toObject = function(opt_includeInstance) {
  return proto.neuracore_types.LanguageData.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.neuracore_types.LanguageData} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.neuracore_types.LanguageData.toObject = function(includeInstance, msg) {
  var f, obj = {
timestamp: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0),
text: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.neuracore_types.LanguageData}
 */
proto.neuracore_types.LanguageData.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.neuracore_types.LanguageData;
  return proto.neuracore_types.LanguageData.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.neuracore_types.LanguageData} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.neuracore_types.LanguageData}
 */
proto.neuracore_types.LanguageData.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setTimestamp(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setText(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.neuracore_types.LanguageData.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.neuracore_types.LanguageData.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.neuracore_types.LanguageData} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.neuracore_types.LanguageData.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTimestamp();
  if (f !== 0.0) {
    writer.writeDouble(
      1,
      f
    );
  }
  f = message.getText();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional double timestamp = 1;
 * @return {number}
 */
proto.neuracore_types.LanguageData.prototype.getTimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.neuracore_types.LanguageData} returns this
 */
proto.neuracore_types.LanguageData.prototype.setTimestamp = function(value) {
  return jspb.Message.setProto3FloatField(this, 1, value);
};


/**
 * optional string text = 2;
 * @return {string}
 */
proto.neuracore_types.LanguageData.prototype.getText = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.neuracore_types.LanguageData} returns this
 */
proto.neuracore_types.LanguageData.prototype.setText = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.neuracore_types.CustomData.prototype.toObject = function(opt_includeInstance) {
  return proto.neuracore_types.CustomData.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.neuracore_types.CustomData} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.neuracore_types.CustomData.toObject = function(includeInstance, msg) {
  var f, obj = {
timestamp: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0),
data: msg.getData_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.neuracore_types.CustomData}
 */
proto.neuracore_types.CustomData.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.neuracore_types.CustomData;
  return proto.neuracore_types.CustomData.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.neuracore_types.CustomData} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.neuracore_types.CustomData}
 */
proto.neuracore_types.CustomData.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setTimestamp(value);
      break;
    case 2:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setData(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.neuracore_types.CustomData.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.neuracore_types.CustomData.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.neuracore_types.CustomData} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.neuracore_types.CustomData.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTimestamp();
  if (f !== 0.0) {
    writer.writeDouble(
      1,
      f
    );
  }
  f = message.getData_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      2,
      f
    );
  }
};


/**
 * optional double timestamp = 1;
 * @return {number}
 */
proto.neuracore_types.CustomData.prototype.getTimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.neuracore_types.CustomData} returns this
 */
proto.neuracore_types.CustomData.prototype.setTimestamp = function(value) {
  return jspb.Message.setProto3FloatField(this, 1, value);
};


/**
 * optional bytes data = 2;
 * @return {!(string|Uint8Array)}
 */
proto.neuracore_types.CustomData.prototype.getData = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * optional bytes data = 2;
 * This is a type-conversion wrapper around `getData()`
 * @return {string}
 */
proto.neuracore_types.CustomData.prototype.getData_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getData()));
};


/**
 * optional bytes data = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getData()`
 * @return {!Uint8Array}
 */
proto.neuracore_types.CustomData.prototype.getData_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getData()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.neuracore_types.CustomData} returns this
 */
proto.neuracore_types.CustomData.prototype.setData = function(value) {
  return jspb.Message.setProto3BytesField(this, 2, value);
};


goog.object.extend(exports, proto.neuracore_types);
