name: PR Changelog Reminder

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - labeled
      - unlabeled
      - synchronize

jobs:
  suggest-changelog-update:
    uses: NeuracoreAI/shared-workflows/.github/workflows/pr-changelog-reminder.yaml@main
    permissions:
      pull-requests: write
