name: PR Check Label

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

jobs:
  check-version-label:
    uses: NeuracoreAI/shared-workflows/.github/workflows/pr-check-label.yaml@main
